In [1]:
# Tanmay Sharma 
# Feb 9 2022
# week 2 

"""
-import apple data base from Google Draw, take random sample of 100 apples, pick first apple in that set
and visualize it
-change all values in matrix that are above 0 to 1; the difference between 234 and 1 is not 
recognized in the image as it black and white
-adjust the random sample method to be more efficient
-test with a one-dimensional array; adjust from the current 2d array
-create training set for apples // download images similar to shape of apple for training set
 
 
 
 
 """

'\n-import apple data base from Google Draw, take random sample of 100 apples, pick first apple in that set\nand visualize it\n-change all values in matrix that are above 0 to 1; the difference between 234 and 1 is not \nrecognized in the image as it black and white\n-adjust the random sample method to be more efficient\n-test with a one-dimensional array; adjust from the current 2d array\n-create training set for apples // download images similar to shape of apple for training set\n \n \n \n \n '

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import numpy as np
from matplotlib import pyplot as plt
#import matplotlib
#import glob
import random
from PIL import Image as im



In [6]:

apples_df = np.load("apple.npy")
print(apples_df.shape)

jobs=[]
rand=0
for i in range(100):
    rand = random.randint(1,784)
    jobs.append(rand)
#print(jobs)
#print(apples_df[jobs[0]])

    
dataset = apples_df[jobs[0]]



array = np.reshape(dataset, (28, 28))
"""
x=0
y=0
i = 0
for i in range(1,28):
    if (array[i][y] != 0):
        array[i][y] = 1
"""
i=0
t= 0
for i in range(1,28):
    for t in range(1,28):
        if (array[t][i] != 0):
            array[t][i] = 1
  

print(array)

data = im.fromarray(array)


    # saving the final output 
    # as a PNG file
data.save('apple.png')


"""
for filename in glob.glob("data.npy"):
    if '.npy' in filename:
        img_array = np.load(filename, allow_pickle=True)
        plt.imshow(img_array, cmap="gray")
        img_name = filename+".png"
        matplotlib.image.imsave(img_name, img_array)
        print(filename)

"""
"""
np.save('data.npy', data)
print(apples_df)
random_index1 = np.random.randint(1, apples_df.shape[1])
random_index2 = np.random.randint(1, apples_df.shape[1])
selectedApple = apples_df[random_index1][random_index2]
print(selectedApple)
"""

(144722, 784)
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 1 

"\nnp.save('data.npy', data)\nprint(apples_df)\nrandom_index1 = np.random.randint(1, apples_df.shape[1])\nrandom_index2 = np.random.randint(1, apples_df.shape[1])\nselectedApple = apples_df[random_index1][random_index2]\nprint(selectedApple)\n"